// v2.17.0 — Role-specific report bundles for VP Sales, CFO, CEO views.
// Reads everything out of KV via snapshots.ts and swot.ts. Lazily seeds
// role view configs on first call so we don't need a migration step.

import type { KVNamespace } from '@cloudflare/workers-types';
import { listSnapshots } from './snapshots';
import { listSwot }      from './swot';

const TAG_BY_ROLE: Record<string, string> = {
  'vp-sales': 'Sales',
  'cfo':      'Finance',
  'ceo':      'Strategic',
};

const HEADLINE_METRICS = [
  'revenue_paid','active_clients','cash_position',
  'gross_margin_pct','dso_days','ar_overdue',
] as const;

const DEFAULT_ROLE_CONFIGS: Record<string, any> = {
  'vp-sales': {
    title: 'VP Sales — Operating View',
    widgets: [
      { id:'new_business_mom',     title:'New Business (revenue + count, MoM)', metric:'revenue_invoiced' },
      { id:'client_type_mix',      title:'Client Type Mix',                      breakdown:'clientType' },
      { id:'avg_deal_size',        title:'Average Deal Size MoM' },
      { id:'top10_active_revenue', title:'Top 10 Active Clients — Last 90 Days' },
      { id:'renewals_60d',         title:'Renewals Due in 60 Days' },
      { id:'swot_panel',           title:'SWOT — Sales',                          tag:'Sales' },
    ],
  },
  'cfo': {
    title: 'CFO — Treasury & Risk',
    widgets: [
      { id:'cash_position_today',  title:'Cash Position (today, 7d, 13w)' },
      { id:'dso_trend_12m',        title:'DSO — 12-Month Trend' },
      { id:'gross_margin_mom_yoy', title:'Gross Margin — MoM and YoY' },
      { id:'ar_aging_buckets',     title:'AR Aging Buckets with Trend Arrows' },
      { id:'overdue_concentration',title:'Top 10 Overdue Clients' },
      { id:'bank_tab_full',        title:'Bank Tab — Full' },
      { id:'swot_panel',           title:'SWOT — Finance',                       tag:'Finance' },
    ],
  },
  'ceo': {
    title: 'CEO — Top-Line View',
    widgets: [
      { id:'headline_kpis',        title:'Revenue MoM/YoY · Cash · Gross Margin · Runway' },
      { id:'goals_progress',       title:'Goals Progress (revenue, clients, collection)' },
      { id:'bank_approval_signal', title:'Bank Approval Indicator' },
      { id:'swot_strategic',       title:'SWOT — Strategic',                     tag:'Strategic' },
      { id:'what_changed',         title:'What Changed This Month',              autoGenerated: true },
    ],
  },
};

function ensureKv(kv: KVNamespace | undefined): asserts kv is KVNamespace {
  if (!kv) throw new Error('GOALS_KV not configured');
}

const cfgKey = (t: number, role: string) => `role-view:${t}:${role}`;

export async function getRoleConfig(kv: KVNamespace, role: string, tenantId = 1) {
  ensureKv(kv);
  const v = await kv.get(cfgKey(tenantId, role));
  if (v) return JSON.parse(v);
  // Lazy seed — first request after deploy populates the default.
  const def = DEFAULT_ROLE_CONFIGS[role];
  if (!def) return null;
  await kv.put(cfgKey(tenantId, role), JSON.stringify(def));
  return def;
}

export async function setRoleConfig(kv: KVNamespace, role: string, config: any, tenantId = 1) {
  ensureKv(kv);
  await kv.put(cfgKey(tenantId, role), JSON.stringify(config));
  return config;
}

export async function buildReport(kv: KVNamespace, role: string, tenantId = 1) {
  ensureKv(kv);
  role = role.toLowerCase();

  const config = await getRoleConfig(kv, role, tenantId);
  if (!config) throw new Error(`No view configured for role: ${role}`);

  // Last 12 snapshots (most recent first) → reverse to ascending for charts.
  const snaps = await listSnapshots(kv, {}, tenantId);
  const history = snaps.slice(0, 12).reverse();
  const current = history.at(-1) || null;

  // SWOT scoped to role's tag (current quarter + ongoing).
  const tag = TAG_BY_ROLE[role] || null;
  let swot: any[] = [];
  if (tag) {
    const now = new Date();
    const q = `${now.getUTCFullYear()}-Q${Math.ceil((now.getUTCMonth() + 1) / 3)}`;
    const all = await listSwot(kv, { tag }, tenantId);
    swot = all.filter(e => e.period === 'ongoing' || e.period === q);
  }

  const deltas: Record<string, any> = {};
  for (const m of HEADLINE_METRICS) deltas[m] = computeDelta(history, m);

  const narrative = role === 'ceo' && current ? buildNarrative(deltas) : null;

  return { role, config, current, history, swot, deltas, narrative };
}

function computeDelta(rows: any[], metric: string) {
  const n = rows.length;
  if (n < 1) return { cur: null };
  const cur = rows[n - 1][metric] != null ? Number(rows[n - 1][metric]) : null;
  const out: any = { cur };
  if (n >= 2) {
    const prev = rows[n - 2][metric] != null ? Number(rows[n - 2][metric]) : null;
    if (prev !== null && prev !== 0 && cur !== null) {
      out.mom_pct = Math.round(((cur - prev) / prev * 100) * 100) / 100;
    }
    if (prev !== null && cur !== null) out.mom_abs = Math.round((cur - prev) * 100) / 100;
  }
  return out;
}

function buildNarrative(d: Record<string, any>): string {
  const bits: string[] = [];
  const fmtUSD = (n: number) => '$' + Math.round(n).toLocaleString('en-US');
  const rev = d.revenue_paid, cash = d.cash_position, ovd = d.ar_overdue;
  if (rev?.mom_pct != null && rev?.cur != null) {
    bits.push(`Revenue ${rev.mom_pct >= 0 ? 'up' : 'down'} ${Math.abs(rev.mom_pct).toFixed(1)}% MoM (${fmtUSD(rev.cur)}).`);
  }
  if (cash?.mom_abs != null) {
    bits.push(`Cash position ${cash.mom_abs >= 0 ? 'increased' : 'decreased'} by ${fmtUSD(Math.abs(cash.mom_abs))}.`);
  }
  if (ovd?.mom_abs != null) {
    bits.push(`Overdue AR ${ovd.mom_abs <= 0 ? 'fell' : 'rose'} by ${fmtUSD(Math.abs(ovd.mom_abs))}.`);
  }
  return bits.length ? bits.join(' ') : 'Not enough history yet for a narrative.';
}
