-- v2.17.0 — default role view configs.
INSERT OR REPLACE INTO role_views (tenant_id, role, config_json, updated_at) VALUES
(1, 'vp-sales',
  json_object(
    'title', 'VP Sales — Operating View',
    'widgets', json_array(
      json_object('id','new_business_mom',     'title','New Business (revenue + count, MoM)', 'metric','revenue_invoiced'),
      json_object('id','client_type_mix',      'title','Client Type Mix',                      'breakdown','clientType'),
      json_object('id','avg_deal_size',        'title','Average Deal Size MoM'),
      json_object('id','top10_active_revenue', 'title','Top 10 Active Clients — Last 90 Days'),
      json_object('id','renewals_60d',         'title','Renewals Due in 60 Days'),
      json_object('id','swot_panel',           'title','SWOT — Sales',                         'tag','Sales')
    )
  ),
  datetime('now')),
(1, 'cfo',
  json_object(
    'title', 'CFO — Treasury & Risk',
    'widgets', json_array(
      json_object('id','cash_position_today',  'title','Cash Position (today, 7d, 13w)'),
      json_object('id','dso_trend_12m',        'title','DSO — 12-Month Trend'),
      json_object('id','gross_margin_mom_yoy', 'title','Gross Margin — MoM and YoY'),
      json_object('id','ar_aging_buckets',     'title','AR Aging Buckets with Trend Arrows'),
      json_object('id','overdue_concentration','title','Top 10 Overdue Clients'),
      json_object('id','bank_tab_full',        'title','Bank Tab — Full'),
      json_object('id','swot_panel',           'title','SWOT — Finance',                       'tag','Finance')
    )
  ),
  datetime('now')),
(1, 'ceo',
  json_object(
    'title', 'CEO — Top-Line View',
    'widgets', json_array(
      json_object('id','headline_kpis',        'title','Revenue MoM/YoY · Cash · Gross Margin · Runway'),
      json_object('id','goals_progress',       'title','Goals Progress (revenue, clients, collection)'),
      json_object('id','bank_approval_signal', 'title','Bank Approval Indicator'),
      json_object('id','swot_strategic',       'title','SWOT — Strategic',                     'tag','Strategic'),
      json_object('id','what_changed',         'title','What Changed This Month',              'autoGenerated', 1)
    )
  ),
  datetime('now'));
